### ISSUE TITLE
swaggerのエンドポイント＋データ構造（created_by）の名称を修正する

### ISSUE THREAD

**Issue by s9-sukyu** [traPtitech/Emoine_R#28]

**Comment by HinaruhiGithub** [comment]
これって、パスの設計がcomment/${meeting_id}→meetings/${meeting_id}/comments
とかの変更のことを表してますか？

**Comment by s9-sukyu** [comment]
はい

**Comment by HinaruhiGithub** [comment]
既存のエンドポイントに/meetingが存在してますが、今回の変更/meeting**s**/.....................であってますか？

**Comment by s9-sukyu** [comment]
sつけなくていいかもです

**Comment by HinaruhiGithub** [comment]
了解です。
ではいったんsつけない方針でいきます。
